//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelXmlQueryResults.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ExcelXmlQueryResults.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppconfigBroken {
            get {
                return ResourceManager.GetString("AppconfigBroken", resourceCulture);
            }
        }
        
        internal static string DefaultColumnType {
            get {
                return ResourceManager.GetString("DefaultColumnType", resourceCulture);
            }
        }
        
        internal static string DefaultMaxRowsPerSheet {
            get {
                return ResourceManager.GetString("DefaultMaxRowsPerSheet", resourceCulture);
            }
        }
        
        internal static string DefaultQueryTimeout {
            get {
                return ResourceManager.GetString("DefaultQueryTimeout", resourceCulture);
            }
        }
        
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        internal static string NewResultSetWorkbook {
            get {
                return ResourceManager.GetString("NewResultSetWorkbook", resourceCulture);
            }
        }
        
        internal static string NewResultSetWorksheet {
            get {
                return ResourceManager.GetString("NewResultSetWorksheet", resourceCulture);
            }
        }
        
        internal static string NoApprFile {
            get {
                return ResourceManager.GetString("NoApprFile", resourceCulture);
            }
        }
        
        internal static string RunningNoResults {
            get {
                return ResourceManager.GetString("RunningNoResults", resourceCulture);
            }
        }
        
        internal static string RunningSomeResults {
            get {
                return ResourceManager.GetString("RunningSomeResults", resourceCulture);
            }
        }
        
        internal static string SaveDialogFilter {
            get {
                return ResourceManager.GetString("SaveDialogFilter", resourceCulture);
            }
        }
        
        internal static string SSPIConnection {
            get {
                return ResourceManager.GetString("SSPIConnection", resourceCulture);
            }
        }
        
        internal static string StateSettingsConfigSection {
            get {
                return ResourceManager.GetString("StateSettingsConfigSection", resourceCulture);
            }
        }
        
        internal static string TooltipInitialFilename {
            get {
                return ResourceManager.GetString("TooltipInitialFilename", resourceCulture);
            }
        }
        
        internal static string TooltipResultNames {
            get {
                return ResourceManager.GetString("TooltipResultNames", resourceCulture);
            }
        }
        
        internal static string UsernamePasswordConnection {
            get {
                return ResourceManager.GetString("UsernamePasswordConnection", resourceCulture);
            }
        }
        
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string FileTypeXlsx {
            get {
                return ResourceManager.GetString("FileTypeXlsx", resourceCulture);
            }
        }
        
        internal static string FileTypeXml {
            get {
                return ResourceManager.GetString("FileTypeXml", resourceCulture);
            }
        }
        
        internal static string MaxSize {
            get {
                return ResourceManager.GetString("MaxSize", resourceCulture);
            }
        }
        
        internal static string DupeKeyColumnsToolTip {
            get {
                return ResourceManager.GetString("DupeKeyColumnsToolTip", resourceCulture);
            }
        }
    }
}
