//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelXmlQueryResults.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelXmlQueryResults.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed config file. Edit and/or restore from the default xml config file..
        /// </summary>
        internal static string AppconfigBroken {
            get {
                return ResourceManager.GetString("AppconfigBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string DefaultColumnType {
            get {
                return ResourceManager.GetString("DefaultColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100000.
        /// </summary>
        internal static string DefaultMaxRowsPerSheet {
            get {
                return ResourceManager.GetString("DefaultMaxRowsPerSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string DefaultQueryTimeout {
            get {
                return ResourceManager.GetString("DefaultQueryTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xlsx.
        /// </summary>
        internal static string FileTypeXlsx {
            get {
                return ResourceManager.GetString("FileTypeXlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml.
        /// </summary>
        internal static string FileTypeXml {
            get {
                return ResourceManager.GetString("FileTypeXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished; awaiting user action..
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum uncompressed total size of all worksheets, in gigabytes. If this value is exceeded before starting a new worksheet, writing output stops. Empirical evidence suggests the default of around 2.5 is safe..
        /// </summary>
        internal static string MaxSize {
            get {
                return ResourceManager.GetString("MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook.
        /// </summary>
        internal static string NewResultSetWorkbook {
            get {
                return ResourceManager.GetString("NewResultSetWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet.
        /// </summary>
        internal static string NewResultSetWorksheet {
            get {
                return ResourceManager.GetString("NewResultSetWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an appropriate file for output..
        /// </summary>
        internal static string NoApprFile {
            get {
                return ResourceManager.GetString("NoApprFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query executing, no results yet..
        /// </summary>
        internal static string RunningNoResults {
            get {
                return ResourceManager.GetString("RunningNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query executing;.
        /// </summary>
        internal static string RunningSomeResults {
            get {
                return ResourceManager.GetString("RunningSomeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Workbook (*.xlsx)|*.xlsx|XML Spreadsheet 2003 (*.xml)|*.xml|All Files (*.*)|*.*.
        /// </summary>
        internal static string SaveDialogFilter {
            get {
                return ResourceManager.GetString("SaveDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSPI.
        /// </summary>
        internal static string SSPIConnection {
            get {
                return ResourceManager.GetString("SSPIConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExcelXmlWriterStateSettings.
        /// </summary>
        internal static string StateSettingsConfigSection {
            get {
                return ResourceManager.GetString("StateSettingsConfigSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial filename to write the XML data to.
        ///If new result sets are written to new workbooks, the second result set will be written to a filename with a &quot;2&quot; appended.
        ///Then, the third result set will be written to a filename with a &quot;3&quot; appended, etc..
        /// </summary>
        internal static string TooltipInitialFilename {
            get {
                return ResourceManager.GetString("TooltipInitialFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can name the worksheet of the corresponding result set.
        ///Otherwise, the first result set will be named Sheet1, the second Sheet2, etc..
        /// </summary>
        internal static string TooltipResultNames {
            get {
                return ResourceManager.GetString("TooltipResultNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Password.
        /// </summary>
        internal static string UsernamePasswordConnection {
            get {
                return ResourceManager.GetString("UsernamePasswordConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Results to Xlsx Frontend v0.33.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting user action..
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
    }
}
