//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelXmlWriter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelXmlWriter.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed config file. Restore the default xml config file..
        /// </summary>
        internal static string AppconfigBroken {
            get {
                return ResourceManager.GetString("AppconfigBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Column ss:Index=&quot;4&quot; ss:StyleID=&quot;s62&quot;/&gt;.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ss:Type=&quot;DateTime&quot;.
        /// </summary>
        internal static string ExcelDataTypeDate {
            get {
                return ResourceManager.GetString("ExcelDataTypeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ss:Type=&quot;Number&quot;.
        /// </summary>
        internal static string ExcelDataTypeNumber {
            get {
                return ResourceManager.GetString("ExcelDataTypeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ss:Type=&quot;String&quot;.
        /// </summary>
        internal static string ExcelDataTypeString {
            get {
                return ResourceManager.GetString("ExcelDataTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string ExcelMaximumNumberLength {
            get {
                return ResourceManager.GetString("ExcelMaximumNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSPI.
        /// </summary>
        internal static string SSPIConnection {
            get {
                return ResourceManager.GetString("SSPIConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Table ss:ExpandedColumnCount=&quot;3&quot; ss:ExpandedRowCount=&quot;2&quot; x:FullColumns=&quot;1&quot;
        ///   x:FullRows=&quot;1&quot; ss:DefaultRowHeight=&quot;15&quot;&gt;.
        /// </summary>
        internal static string TableHeader {
            get {
                return ResourceManager.GetString("TableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Password.
        /// </summary>
        internal static string UsernamePasswordConnection {
            get {
                return ResourceManager.GetString("UsernamePasswordConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified stream doesn&apos;t support writing, cannot write workbook output..
        /// </summary>
        internal static string WorkbookCannotWrite {
            get {
                return ResourceManager.GetString("WorkbookCannotWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;?mso-application progid=&quot;Excel.Sheet&quot;?&gt;
        ///&lt;Workbook xmlns=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        /// xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        /// xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot;
        /// xmlns:ss=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        /// xmlns:html=&quot;http://www.w3.org/TR/REC-html40&quot;&gt;
        /// &lt;DocumentProperties xmlns=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///  &lt;Author&gt;djfrye&lt;/Author&gt;
        ///  &lt;LastAuthor&gt;djfrye&lt;/LastAuthor&gt;
        ///  &lt;Created&gt;2009-12-08T22:42:48Z&lt;/Created&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkbookHeader {
            get {
                return ResourceManager.GetString("WorkbookHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook hasn&apos;t yet retrieved data!.
        /// </summary>
        internal static string WorkbookNotStarted {
            get {
                return ResourceManager.GetString("WorkbookNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Styles&gt;
        ///  &lt;Style ss:ID=&quot;Default&quot; ss:Name=&quot;Normal&quot;&gt;
        ///   &lt;Alignment ss:Vertical=&quot;Bottom&quot;/&gt;
        ///   &lt;Borders/&gt;
        ///   &lt;Font ss:FontName=&quot;Calibri&quot; x:Family=&quot;Swiss&quot; ss:Size=&quot;11&quot; ss:Color=&quot;#000000&quot;/&gt;
        ///   &lt;Interior/&gt;
        ///   &lt;NumberFormat/&gt;
        ///   &lt;Protection/&gt;
        ///  &lt;/Style&gt;
        ///  &lt;!-- date --&gt;
        ///  &lt;Style ss:ID=&quot;s63&quot;&gt;
        ///   &lt;NumberFormat ss:Format=&quot;Short Date&quot;/&gt;
        ///  &lt;/Style&gt;
        /// &lt;/Styles&gt;.
        /// </summary>
        internal static string WorkbookStyles {
            get {
                return ResourceManager.GetString("WorkbookStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook still writing data!.
        /// </summary>
        internal static string WorkbookUnfinished {
            get {
                return ResourceManager.GetString("WorkbookUnfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Worksheet ss:Name=&quot;Sheet1&quot;&gt;.
        /// </summary>
        internal static string WorksheetHeader {
            get {
                return ResourceManager.GetString("WorksheetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;WorksheetOptions xmlns=&quot;urn:schemas-microsoft-com:office:excel&quot;&gt;
        ///   &lt;PageSetup&gt;
        ///    &lt;Header x:Margin=&quot;0.3&quot;/&gt;
        ///    &lt;Footer x:Margin=&quot;0.3&quot;/&gt;
        ///    &lt;PageMargins x:Bottom=&quot;0.75&quot; x:Left=&quot;0.7&quot; x:Right=&quot;0.7&quot; x:Top=&quot;0.75&quot;/&gt;
        ///   &lt;/PageSetup&gt;
        ///   &lt;Unsynced/&gt;
        ///   &lt;Print&gt;
        ///    &lt;ValidPrinterInfo/&gt;
        ///    &lt;HorizontalResolution&gt;600&lt;/HorizontalResolution&gt;
        ///    &lt;VerticalResolution&gt;600&lt;/VerticalResolution&gt;
        ///   &lt;/Print&gt;
        ///   &lt;Selected/&gt;
        ///   &lt;FreezePanes/&gt;
        ///   &lt;FrozenNoSplit/&gt;
        ///   &lt;SplitHorizontal&gt;1&lt;/SplitHorizontal&gt;
        ///   &lt;TopRo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorksheetOptions {
            get {
                return ResourceManager.GetString("WorksheetOptions", resourceCulture);
            }
        }
    }
}
