//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelXmlWriter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<styleSheet xmlns=""http://schemas.openxmlformats.org/spreadsheetml/2006/main"">
  <fonts count=""1"">
    <font>
      <sz val=""11"" />
      <color theme=""1"" />
      <name val=""Calibri"" />
      <family val=""2"" />
      <scheme val=""minor"" />
    </font>
  </fonts>
  <fills count=""2"">
    <fill>
      <patternFill patternType=""none"" />
    </fill>
    <fill>
      <patternFill patternType=""gray125"" />
    </fill>
  </fills>
  <borders count=""1"">
    <border>
      <left />
      <right />
      <top />
      <bottom />
      <diagonal />
    </border>
  </borders>
  <cellStyleXfs count=""1"">
    <xf numFmtId=""0"" fontId=""0"" fillId=""0"" borderId=""0"" />
  </cellStyleXfs>
  <cellXfs count=""2"">
    <xf numFmtId=""0"" fontId=""0"" fillId=""0"" borderId=""0"" xfId=""0"" />
    <xf numFmtId=""14"" fontId=""0"" fillId=""0"" borderId=""0"" xfId=""0"" applyNumberFormat=""1"" />
  </cellXfs>
  <cellStyles count=""1"">
    <cellStyle name=""Normal"" xfId=""0"" builtinId=""0"" />
  </cellStyles>
  <dxfs count=""0"" />
  <tableStyles count=""0"" defaultTableStyle=""TableStyleMedium9"" defaultPivotStyle=""PivotStyleLight16"" />
</styleSheet>")]
        public global::System.Xml.XmlDocument StylesXml {
            get {
                return ((global::System.Xml.XmlDocument)(this["StylesXml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<cp:coreProperties xmlns:cp=""http://schemas.openxmlformats.org/package/2006/metadata/core-properties"" xmlns:dc=""http://purl.org/dc/elements/1.1/"" xmlns:dcterms=""http://purl.org/dc/terms/"" xmlns:dcmitype=""http://purl.org/dc/dcmitype/"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <dc:creator>ExcelXml</dc:creator>
  <cp:lastModifiedBy>ExcelXml</cp:lastModifiedBy>
  <dcterms:created xsi:type=""dcterms:W3CDTF"">2010-05-17T22:42:26Z</dcterms:created>
  <dcterms:modified xsi:type=""dcterms:W3CDTF"">2010-05-17T22:53:09Z</dcterms:modified>
</cp:coreProperties>")]
        public global::System.Xml.XmlDocument CoreXml {
            get {
                return ((global::System.Xml.XmlDocument)(this["CoreXml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<a:theme xmlns:a=\"http://schemas.openxml" +
            "formats.org/drawingml/2006/main\" name=\"Office Theme\">\r\n  <a:themeElements>\r\n    " +
            "<a:clrScheme name=\"Office\">\r\n      <a:dk1>\r\n        <a:sysClr val=\"windowText\" l" +
            "astClr=\"000000\" />\r\n      </a:dk1>\r\n      <a:lt1>\r\n        <a:sysClr val=\"window" +
            "\" lastClr=\"FFFFFF\" />\r\n      </a:lt1>\r\n      <a:dk2>\r\n        <a:srgbClr val=\"1F" +
            "497D\" />\r\n      </a:dk2>\r\n      <a:lt2>\r\n        <a:srgbClr val=\"EEECE1\" />\r\n   " +
            "   </a:lt2>\r\n      <a:accent1>\r\n        <a:srgbClr val=\"4F81BD\" />\r\n      </a:ac" +
            "cent1>\r\n      <a:accent2>\r\n        <a:srgbClr val=\"C0504D\" />\r\n      </a:accent2" +
            ">\r\n      <a:accent3>\r\n        <a:srgbClr val=\"9BBB59\" />\r\n      </a:accent3>\r\n  " +
            "    <a:accent4>\r\n        <a:srgbClr val=\"8064A2\" />\r\n      </a:accent4>\r\n      <" +
            "a:accent5>\r\n        <a:srgbClr val=\"4BACC6\" />\r\n      </a:accent5>\r\n      <a:acc" +
            "ent6>\r\n        <a:srgbClr val=\"F79646\" />\r\n      </a:accent6>\r\n      <a:hlink>\r\n" +
            "        <a:srgbClr val=\"0000FF\" />\r\n      </a:hlink>\r\n      <a:folHlink>\r\n      " +
            "  <a:srgbClr val=\"800080\" />\r\n      </a:folHlink>\r\n    </a:clrScheme>\r\n    <a:fo" +
            "ntScheme name=\"Office\">\r\n      <a:majorFont>\r\n        <a:latin typeface=\"Cambria" +
            "\" />\r\n        <a:ea typeface=\"\" />\r\n        <a:cs typeface=\"\" />\r\n        <a:fon" +
            "t script=\"Jpan\" typeface=\"ＭＳ Ｐゴシック\" />\r\n        <a:font script=\"Hang\" typeface=\"" +
            "맑은 고딕\" />\r\n        <a:font script=\"Hans\" typeface=\"宋体\" />\r\n        <a:font scrip" +
            "t=\"Hant\" typeface=\"新細明體\" />\r\n        <a:font script=\"Arab\" typeface=\"Times New R" +
            "oman\" />\r\n        <a:font script=\"Hebr\" typeface=\"Times New Roman\" />\r\n        <" +
            "a:font script=\"Thai\" typeface=\"Tahoma\" />\r\n        <a:font script=\"Ethi\" typefac" +
            "e=\"Nyala\" />\r\n        <a:font script=\"Beng\" typeface=\"Vrinda\" />\r\n        <a:fon" +
            "t script=\"Gujr\" typeface=\"Shruti\" />\r\n        <a:font script=\"Khmr\" typeface=\"Mo" +
            "olBoran\" />\r\n        <a:font script=\"Knda\" typeface=\"Tunga\" />\r\n        <a:font " +
            "script=\"Guru\" typeface=\"Raavi\" />\r\n        <a:font script=\"Cans\" typeface=\"Euphe" +
            "mia\" />\r\n        <a:font script=\"Cher\" typeface=\"Plantagenet Cherokee\" />\r\n     " +
            "   <a:font script=\"Yiii\" typeface=\"Microsoft Yi Baiti\" />\r\n        <a:font scrip" +
            "t=\"Tibt\" typeface=\"Microsoft Himalaya\" />\r\n        <a:font script=\"Thaa\" typefac" +
            "e=\"MV Boli\" />\r\n        <a:font script=\"Deva\" typeface=\"Mangal\" />\r\n        <a:f" +
            "ont script=\"Telu\" typeface=\"Gautami\" />\r\n        <a:font script=\"Taml\" typeface=" +
            "\"Latha\" />\r\n        <a:font script=\"Syrc\" typeface=\"Estrangelo Edessa\" />\r\n     " +
            "   <a:font script=\"Orya\" typeface=\"Kalinga\" />\r\n        <a:font script=\"Mlym\" ty" +
            "peface=\"Kartika\" />\r\n        <a:font script=\"Laoo\" typeface=\"DokChampa\" />\r\n    " +
            "    <a:font script=\"Sinh\" typeface=\"Iskoola Pota\" />\r\n        <a:font script=\"Mo" +
            "ng\" typeface=\"Mongolian Baiti\" />\r\n        <a:font script=\"Viet\" typeface=\"Times" +
            " New Roman\" />\r\n        <a:font script=\"Uigh\" typeface=\"Microsoft Uighur\" />\r\n  " +
            "    </a:majorFont>\r\n      <a:minorFont>\r\n        <a:latin typeface=\"Calibri\" />\r" +
            "\n        <a:ea typeface=\"\" />\r\n        <a:cs typeface=\"\" />\r\n        <a:font scr" +
            "ipt=\"Jpan\" typeface=\"ＭＳ Ｐゴシック\" />\r\n        <a:font script=\"Hang\" typeface=\"맑은 고딕" +
            "\" />\r\n        <a:font script=\"Hans\" typeface=\"宋体\" />\r\n        <a:font script=\"Ha" +
            "nt\" typeface=\"新細明體\" />\r\n        <a:font script=\"Arab\" typeface=\"Arial\" />\r\n     " +
            "   <a:font script=\"Hebr\" typeface=\"Arial\" />\r\n        <a:font script=\"Thai\" type" +
            "face=\"Tahoma\" />\r\n        <a:font script=\"Ethi\" typeface=\"Nyala\" />\r\n        <a:" +
            "font script=\"Beng\" typeface=\"Vrinda\" />\r\n        <a:font script=\"Gujr\" typeface=" +
            "\"Shruti\" />\r\n        <a:font script=\"Khmr\" typeface=\"DaunPenh\" />\r\n        <a:fo" +
            "nt script=\"Knda\" typeface=\"Tunga\" />\r\n        <a:font script=\"Guru\" typeface=\"Ra" +
            "avi\" />\r\n        <a:font script=\"Cans\" typeface=\"Euphemia\" />\r\n        <a:font s" +
            "cript=\"Cher\" typeface=\"Plantagenet Cherokee\" />\r\n        <a:font script=\"Yiii\" t" +
            "ypeface=\"Microsoft Yi Baiti\" />\r\n        <a:font script=\"Tibt\" typeface=\"Microso" +
            "ft Himalaya\" />\r\n        <a:font script=\"Thaa\" typeface=\"MV Boli\" />\r\n        <a" +
            ":font script=\"Deva\" typeface=\"Mangal\" />\r\n        <a:font script=\"Telu\" typeface" +
            "=\"Gautami\" />\r\n        <a:font script=\"Taml\" typeface=\"Latha\" />\r\n        <a:fon" +
            "t script=\"Syrc\" typeface=\"Estrangelo Edessa\" />\r\n        <a:font script=\"Orya\" t" +
            "ypeface=\"Kalinga\" />\r\n        <a:font script=\"Mlym\" typeface=\"Kartika\" />\r\n     " +
            "   <a:font script=\"Laoo\" typeface=\"DokChampa\" />\r\n        <a:font script=\"Sinh\" " +
            "typeface=\"Iskoola Pota\" />\r\n        <a:font script=\"Mong\" typeface=\"Mongolian Ba" +
            "iti\" />\r\n        <a:font script=\"Viet\" typeface=\"Arial\" />\r\n        <a:font scri" +
            "pt=\"Uigh\" typeface=\"Microsoft Uighur\" />\r\n      </a:minorFont>\r\n    </a:fontSche" +
            "me>\r\n    <a:fmtScheme name=\"Office\">\r\n      <a:fillStyleLst>\r\n        <a:solidFi" +
            "ll>\r\n          <a:schemeClr val=\"phClr\" />\r\n        </a:solidFill>\r\n        <a:g" +
            "radFill rotWithShape=\"1\">\r\n          <a:gsLst>\r\n            <a:gs pos=\"0\">\r\n    " +
            "          <a:schemeClr val=\"phClr\">\r\n                <a:tint val=\"50000\" />\r\n   " +
            "             <a:satMod val=\"300000\" />\r\n              </a:schemeClr>\r\n          " +
            "  </a:gs>\r\n            <a:gs pos=\"35000\">\r\n              <a:schemeClr val=\"phClr" +
            "\">\r\n                <a:tint val=\"37000\" />\r\n                <a:satMod val=\"30000" +
            "0\" />\r\n              </a:schemeClr>\r\n            </a:gs>\r\n            <a:gs pos=" +
            "\"100000\">\r\n              <a:schemeClr val=\"phClr\">\r\n                <a:tint val=" +
            "\"15000\" />\r\n                <a:satMod val=\"350000\" />\r\n              </a:schemeC" +
            "lr>\r\n            </a:gs>\r\n          </a:gsLst>\r\n          <a:lin ang=\"16200000\" " +
            "scaled=\"1\" />\r\n        </a:gradFill>\r\n        <a:gradFill rotWithShape=\"1\">\r\n   " +
            "       <a:gsLst>\r\n            <a:gs pos=\"0\">\r\n              <a:schemeClr val=\"ph" +
            "Clr\">\r\n                <a:shade val=\"51000\" />\r\n                <a:satMod val=\"1" +
            "30000\" />\r\n              </a:schemeClr>\r\n            </a:gs>\r\n            <a:gs " +
            "pos=\"80000\">\r\n              <a:schemeClr val=\"phClr\">\r\n                <a:shade " +
            "val=\"93000\" />\r\n                <a:satMod val=\"130000\" />\r\n              </a:sch" +
            "emeClr>\r\n            </a:gs>\r\n            <a:gs pos=\"100000\">\r\n              <a:" +
            "schemeClr val=\"phClr\">\r\n                <a:shade val=\"94000\" />\r\n               " +
            " <a:satMod val=\"135000\" />\r\n              </a:schemeClr>\r\n            </a:gs>\r\n " +
            "         </a:gsLst>\r\n          <a:lin ang=\"16200000\" scaled=\"0\" />\r\n        </a:" +
            "gradFill>\r\n      </a:fillStyleLst>\r\n      <a:lnStyleLst>\r\n        <a:ln w=\"9525\"" +
            " cap=\"flat\" cmpd=\"sng\" algn=\"ctr\">\r\n          <a:solidFill>\r\n            <a:sche" +
            "meClr val=\"phClr\">\r\n              <a:shade val=\"95000\" />\r\n              <a:satM" +
            "od val=\"105000\" />\r\n            </a:schemeClr>\r\n          </a:solidFill>\r\n      " +
            "    <a:prstDash val=\"solid\" />\r\n        </a:ln>\r\n        <a:ln w=\"25400\" cap=\"fl" +
            "at\" cmpd=\"sng\" algn=\"ctr\">\r\n          <a:solidFill>\r\n            <a:schemeClr va" +
            "l=\"phClr\" />\r\n          </a:solidFill>\r\n          <a:prstDash val=\"solid\" />\r\n  " +
            "      </a:ln>\r\n        <a:ln w=\"38100\" cap=\"flat\" cmpd=\"sng\" algn=\"ctr\">\r\n      " +
            "    <a:solidFill>\r\n            <a:schemeClr val=\"phClr\" />\r\n          </a:solidF" +
            "ill>\r\n          <a:prstDash val=\"solid\" />\r\n        </a:ln>\r\n      </a:lnStyleLs" +
            "t>\r\n      <a:effectStyleLst>\r\n        <a:effectStyle>\r\n          <a:effectLst>\r\n" +
            "            <a:outerShdw blurRad=\"40000\" dist=\"20000\" dir=\"5400000\" rotWithShape" +
            "=\"0\">\r\n              <a:srgbClr val=\"000000\">\r\n                <a:alpha val=\"380" +
            "00\" />\r\n              </a:srgbClr>\r\n            </a:outerShdw>\r\n          </a:ef" +
            "fectLst>\r\n        </a:effectStyle>\r\n        <a:effectStyle>\r\n          <a:effect" +
            "Lst>\r\n            <a:outerShdw blurRad=\"40000\" dist=\"23000\" dir=\"5400000\" rotWit" +
            "hShape=\"0\">\r\n              <a:srgbClr val=\"000000\">\r\n                <a:alpha va" +
            "l=\"35000\" />\r\n              </a:srgbClr>\r\n            </a:outerShdw>\r\n          " +
            "</a:effectLst>\r\n        </a:effectStyle>\r\n        <a:effectStyle>\r\n          <a:" +
            "effectLst>\r\n            <a:outerShdw blurRad=\"40000\" dist=\"23000\" dir=\"5400000\" " +
            "rotWithShape=\"0\">\r\n              <a:srgbClr val=\"000000\">\r\n                <a:al" +
            "pha val=\"35000\" />\r\n              </a:srgbClr>\r\n            </a:outerShdw>\r\n    " +
            "      </a:effectLst>\r\n          <a:scene3d>\r\n            <a:camera prst=\"orthogr" +
            "aphicFront\">\r\n              <a:rot lat=\"0\" lon=\"0\" rev=\"0\" />\r\n            </a:c" +
            "amera>\r\n            <a:lightRig rig=\"threePt\" dir=\"t\">\r\n              <a:rot lat" +
            "=\"0\" lon=\"0\" rev=\"1200000\" />\r\n            </a:lightRig>\r\n          </a:scene3d>" +
            "\r\n          <a:sp3d>\r\n            <a:bevelT w=\"63500\" h=\"25400\" />\r\n          </" +
            "a:sp3d>\r\n        </a:effectStyle>\r\n      </a:effectStyleLst>\r\n      <a:bgFillSty" +
            "leLst>\r\n        <a:solidFill>\r\n          <a:schemeClr val=\"phClr\" />\r\n        </" +
            "a:solidFill>\r\n        <a:gradFill rotWithShape=\"1\">\r\n          <a:gsLst>\r\n      " +
            "      <a:gs pos=\"0\">\r\n              <a:schemeClr val=\"phClr\">\r\n                <" +
            "a:tint val=\"40000\" />\r\n                <a:satMod val=\"350000\" />\r\n              " +
            "</a:schemeClr>\r\n            </a:gs>\r\n            <a:gs pos=\"40000\">\r\n           " +
            "   <a:schemeClr val=\"phClr\">\r\n                <a:tint val=\"45000\" />\r\n          " +
            "      <a:shade val=\"99000\" />\r\n                <a:satMod val=\"350000\" />\r\n      " +
            "        </a:schemeClr>\r\n            </a:gs>\r\n            <a:gs pos=\"100000\">\r\n  " +
            "            <a:schemeClr val=\"phClr\">\r\n                <a:shade val=\"20000\" />\r\n" +
            "                <a:satMod val=\"255000\" />\r\n              </a:schemeClr>\r\n       " +
            "     </a:gs>\r\n          </a:gsLst>\r\n          <a:path path=\"circle\">\r\n          " +
            "  <a:fillToRect l=\"50000\" t=\"-80000\" r=\"50000\" b=\"180000\" />\r\n          </a:path" +
            ">\r\n        </a:gradFill>\r\n        <a:gradFill rotWithShape=\"1\">\r\n          <a:gs" +
            "Lst>\r\n            <a:gs pos=\"0\">\r\n              <a:schemeClr val=\"phClr\">\r\n     " +
            "           <a:tint val=\"80000\" />\r\n                <a:satMod val=\"300000\" />\r\n  " +
            "            </a:schemeClr>\r\n            </a:gs>\r\n            <a:gs pos=\"100000\">" +
            "\r\n              <a:schemeClr val=\"phClr\">\r\n                <a:shade val=\"30000\" " +
            "/>\r\n                <a:satMod val=\"200000\" />\r\n              </a:schemeClr>\r\n   " +
            "         </a:gs>\r\n          </a:gsLst>\r\n          <a:path path=\"circle\">\r\n      " +
            "      <a:fillToRect l=\"50000\" t=\"50000\" r=\"50000\" b=\"50000\" />\r\n          </a:pa" +
            "th>\r\n        </a:gradFill>\r\n      </a:bgFillStyleLst>\r\n    </a:fmtScheme>\r\n  </a" +
            ":themeElements>\r\n  <a:objectDefaults />\r\n  <a:extraClrSchemeLst />\r\n</a:theme>")]
        public global::System.Xml.XmlDocument ThemeXml {
            get {
                return ((global::System.Xml.XmlDocument)(this["ThemeXml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<sst xmlns=""http://schemas.openxmlformats.org/spreadsheetml/2006/main"">
  <si>
    <t>abc sheet 1</t>
  </si>
  <si>
    <t xml:space=""preserve"">abc sheet 1 </t>
  </si>
  <si>
    <t>b</t>
  </si>
  <si>
    <t>c</t>
  </si>
</sst>")]
        public global::System.Xml.XmlDocument SharedStr {
            get {
                return ((global::System.Xml.XmlDocument)(this["SharedStr"]));
            }
        }
    }
}
